version: '3'
services:
    nextjs:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: nextjs
        ports:
            - 3000:3000
        restart: unless-stopped
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
